import '../models/user_model.dart';
import '../models/house_model.dart';
import '../models/service_model.dart';
import '../models/booking_model.dart';
import '../models/order_model.dart';

class MockDataService {
  // Demo users
  static final List<UserModel> demoUsers = [
    UserModel(
      id: '1',
      name: 'Alex Johnson',
      email: 'alex@student.com',
      phone: '01712345678',
      role: 'student',
      university: 'Subang University',
      profileImage: 'https://i.pravatar.cc/150?img=1',
      address: 'Subang Jaya',
      rating: 4.5,
      reviewCount: 12,
      createdAt: DateTime(2024, 1, 1),
    ),
    UserModel(
      id: '2',
      name: 'Sarah Rahman',
      email: 'sarah@owner.com',
      phone: '01787654321',
      role: 'owner',
      profileImage: 'https://i.pravatar.cc/150?img=5',
      address: 'Dhaka',
      rating: 4.8,
      reviewCount: 45,
      createdAt: DateTime(2023, 6, 15),
    ),
    UserModel(
      id: '3',
      name: 'Karim Restaurant',
      email: 'karim@provider.com',
      phone: '01898765432',
      role: 'provider',
      profileImage: 'https://i.pravatar.cc/150?img=8',
      address: 'Subang Jaya',
      rating: 4.6,
      reviewCount: 89,
      createdAt: DateTime(2023, 3, 10),
    ),
  ];

  // Demo houses
  static final List<HouseModel> demoHouses = [
    HouseModel(
      id: '1',
      ownerId: '2',
      ownerName: 'Sarah Rahman',
      ownerPhone: '01787654321',
      title: 'Campus View Apartments',
      description: 'Modern student accommodation with all amenities. Close to university campus with easy access to public transport.',
      rent: 32000,
      location: 'Subang Jaya',
      area: 'SS15',
      latitude: 3.0738,
      longitude: 101.5183,
      bedrooms: 2,
      bathrooms: 1,
      images: [
        'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
        'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
        'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
      ],
      facilities: ['WiFi', 'AC', 'Parking', 'Security'],
      status: 'available',
      rating: 4.5,
      reviewCount: 12,
      createdAt: DateTime(2024, 1, 15),
      hasWifi: true,
      distanceFromCampus: 1.2,
      roomType: 'Shared Room',
    ),
    HouseModel(
      id: '2',
      ownerId: '2',
      ownerName: 'Sarah Rahman',
      ownerPhone: '01787654321',
      title: 'Sunrise Student Living',
      description: 'Comfortable and affordable student housing with excellent facilities and friendly community.',
      rent: 28000,
      location: 'Subang Jaya',
      area: 'SS14',
      latitude: 3.0812,
      longitude: 101.5249,
      bedrooms: 1,
      bathrooms: 1,
      images: [
        'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
        'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
      ],
      facilities: ['WiFi', 'Laundry', 'Study Room'],
      status: 'available',
      rating: 4.3,
      reviewCount: 8,
      createdAt: DateTime(2024, 2, 1),
      hasWifi: true,
      distanceFromCampus: 1.2,
      roomType: 'Single Room',
    ),
    HouseModel(
      id: '3',
      ownerId: '2',
      ownerName: 'Sarah Rahman',
      ownerPhone: '01787654321',
      title: 'Serene Student Living',
      description: 'Peaceful accommodation perfect for students. Well-maintained and secure environment.',
      rent: 35000,
      location: 'Subang Jaya',
      area: 'SS15',
      latitude: 3.0756,
      longitude: 101.5201,
      bedrooms: 2,
      bathrooms: 2,
      images: [
        'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
        'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
      ],
      facilities: ['WiFi', 'AC', 'Gym', 'Pool'],
      status: 'limited',
      rating: 4.7,
      reviewCount: 15,
      createdAt: DateTime(2024, 1, 20),
      hasWifi: true,
      distanceFromCampus: 0.8,
      roomType: 'Shared Room',
    ),
    HouseModel(
      id: '4',
      ownerId: '2',
      ownerName: 'Sarah Rahman',
      ownerPhone: '01787654321',
      title: 'Modern Studio Rooms',
      description: 'Compact and modern studio rooms with premium facilities.',
      rent: 42000,
      location: 'Petaling Jaya',
      area: 'PJ',
      latitude: 3.1738,
      longitude: 101.5083,
      bedrooms: 1,
      bathrooms: 1,
      images: [
        'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
        'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
      ],
      facilities: ['WiFi', 'AC', 'Kitchen', 'Security'],
      status: 'available',
      rating: 4.6,
      reviewCount: 18,
      createdAt: DateTime(2024, 1, 25),
      hasWifi: true,
      distanceFromCampus: 2.5,
      roomType: 'Single Room',
    ),
    HouseModel(
      id: '5',
      ownerId: '2',
      ownerName: 'Sarah Rahman',
      ownerPhone: '01787654321',
      title: 'Cozy Student Hub',
      description: 'Affordable and cozy accommodation perfect for students on budget.',
      rent: 22000,
      location: 'Subang Jaya',
      area: 'SS13',
      latitude: 3.0605,
      longitude: 101.5143,
      bedrooms: 1,
      bathrooms: 1,
      images: [
        'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
        'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
      ],
      facilities: ['WiFi', 'Shared Kitchen', 'Common Area'],
      status: 'available',
      rating: 4.2,
      reviewCount: 11,
      createdAt: DateTime(2024, 2, 5),
      hasWifi: true,
      distanceFromCampus: 3.2,
      roomType: 'Shared Room',
    ),
    HouseModel(
      id: '6',
      ownerId: '2',
      ownerName: 'Sarah Rahman',
      ownerPhone: '01787654321',
      title: 'Premium Deluxe Living',
      description: 'Luxury student accommodation with high-end amenities and services.',
      rent: 58000,
      location: 'Petaling Jaya',
      area: 'PJ Old Town',
      latitude: 3.1645,
      longitude: 101.5243,
      bedrooms: 2,
      bathrooms: 2,
      images: [
        'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
        'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
        'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
      ],
      facilities: ['WiFi', 'AC', 'Gym', 'Pool', 'Security', 'Parking'],
      status: 'available',
      rating: 4.9,
      reviewCount: 42,
      createdAt: DateTime(2024, 1, 10),
      hasWifi: true,
      distanceFromCampus: 4.8,
      roomType: 'Single Room',
    ),
    HouseModel(
      id: '7',
      ownerId: '2',
      ownerName: 'Sarah Rahman',
      ownerPhone: '01787654321',
      title: 'Budget Friendly Hostel',
      description: 'Very affordable student hostel with basic amenities and social atmosphere.',
      rent: 20000,
      location: 'Subang Jaya',
      area: 'SS16',
      latitude: 3.0895,
      longitude: 101.5312,
      bedrooms: 1,
      bathrooms: 1,
      images: [
        'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
      ],
      facilities: ['WiFi', 'Common Kitchen', 'Recreation Area'],
      status: 'available',
      rating: 4.1,
      reviewCount: 7,
      createdAt: DateTime(2024, 2, 10),
      hasWifi: true,
      distanceFromCampus: 2.1,
      roomType: 'Shared Room',
    ),
    HouseModel(
      id: '8',
      ownerId: '2',
      ownerName: 'Sarah Rahman',
      ownerPhone: '01787654321',
      title: 'Elite Residence Tower',
      description: 'High-rise student residence with modern architecture and facilities.',
      rent: 52000,
      location: 'Petaling Jaya',
      area: 'Damansara',
      latitude: 3.1612,
      longitude: 101.5378,
      bedrooms: 1,
      bathrooms: 1,
      images: [
        'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
        'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
      ],
      facilities: ['WiFi', 'AC', 'Gym', 'Café', 'Security'],
      status: 'available',
      rating: 4.8,
      reviewCount: 35,
      createdAt: DateTime(2024, 1, 12),
      hasWifi: true,
      distanceFromCampus: 5.2,
      roomType: 'Single Room',
    ),
    HouseModel(
      id: '9',
      ownerId: '2',
      ownerName: 'Sarah Rahman',
      ownerPhone: '01787654321',
      title: 'Shared Living Commons',
      description: 'Community-focused accommodation with shared facilities and events.',
      rent: 30000,
      location: 'Subang Jaya',
      area: 'USJ',
      latitude: 3.0542,
      longitude: 101.5087,
      bedrooms: 1,
      bathrooms: 1,
      images: [
        'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
        'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
      ],
      facilities: ['WiFi', 'Common Area', 'Study Room', 'Laundry'],
      status: 'available',
      rating: 4.4,
      reviewCount: 22,
      createdAt: DateTime(2024, 1, 28),
      hasWifi: true,
      distanceFromCampus: 4.5,
      roomType: 'Shared Room',
    ),
    HouseModel(
      id: '10',
      ownerId: '2',
      ownerName: 'Sarah Rahman',
      ownerPhone: '01787654321',
      title: 'Quiet Study Sanctuary',
      description: 'Perfect for serious students looking for peaceful and quiet environment.',
      rent: 38000,
      location: 'Petaling Jaya',
      area: 'Section 51',
      latitude: 3.1742,
      longitude: 101.5145,
      bedrooms: 1,
      bathrooms: 1,
      images: [
        'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
      ],
      facilities: ['WiFi', 'AC', 'Study Desk', 'Library', 'Quiet Hours'],
      status: 'available',
      rating: 4.7,
      reviewCount: 26,
      createdAt: DateTime(2024, 2, 3),
      hasWifi: true,
      distanceFromCampus: 3.8,
      roomType: 'Single Room',
    ),
    HouseModel(
      id: '11',
      ownerId: '2',
      ownerName: 'Sarah Rahman',
      ownerPhone: '01787654321',
      title: 'Vibrant Social Living',
      description: 'Social and energetic accommodation with events, parties and community activities.',
      rent: 25000,
      location: 'Subang Jaya',
      area: 'SS14',
      latitude: 3.0798,
      longitude: 101.5267,
      bedrooms: 1,
      bathrooms: 1,
      images: [
        'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
        'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
      ],
      facilities: ['WiFi', 'Lounge', 'Gaming Room', 'Social Events'],
      status: 'available',
      rating: 4.3,
      reviewCount: 19,
      createdAt: DateTime(2024, 2, 8),
      hasWifi: true,
      distanceFromCampus: 1.5,
      roomType: 'Shared Room',
    ),
  ];

  // Demo services
  static final List<ServiceModel> demoServices = [
    // Food services
    ServiceModel(
      id: 'f1',
      providerId: '3',
      providerName: 'Karim Restaurant',
      providerPhone: '01898765432',
      name: 'Chicken Biryani',
      description: 'Authentic Bangladeshi biryani with tender chicken pieces',
      price: 180,
      category: ServiceCategory.food,
      images: ['https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=400'],
      rating: 4.8,
      reviewCount: 45,
      createdAt: DateTime(2024, 1, 1),
      deliveryTime: '30-45 mins',
    ),
    ServiceModel(
      id: 'f2',
      providerId: '3',
      providerName: 'Karim Restaurant',
      providerPhone: '01898765432',
      name: 'Beef Tehari',
      description: 'Spicy beef tehari with special masala',
      price: 200,
      category: ServiceCategory.food,
      images: ['https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400'],
      rating: 4.6,
      reviewCount: 32,
      createdAt: DateTime(2024, 1, 1),
      deliveryTime: '30-45 mins',
    ),
    ServiceModel(
      id: 'f3',
      providerId: '3',
      providerName: 'Karim Restaurant',
      providerPhone: '01898765432',
      name: 'Mixed Vegetable Curry',
      description: 'Healthy vegetable curry with rice',
      price: 120,
      category: ServiceCategory.food,
      images: ['https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400'],
      rating: 4.4,
      reviewCount: 28,
      createdAt: DateTime(2024, 1, 1),
      deliveryTime: '20-30 mins',
    ),
    // Medicine
    ServiceModel(
      id: 'm1',
      providerId: '3',
      providerName: 'HealthCare Pharmacy',
      providerPhone: '01898765432',
      name: 'Paracetamol 500mg',
      description: 'Pain reliever and fever reducer',
      price: 50,
      category: ServiceCategory.medicine,
      images: ['https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400'],
      rating: 4.9,
      reviewCount: 67,
      createdAt: DateTime(2024, 1, 1),
      deliveryTime: '15-20 mins',
    ),
    ServiceModel(
      id: 'm2',
      providerId: '3',
      providerName: 'HealthCare Pharmacy',
      providerPhone: '01898765432',
      name: 'Vitamin C Tablets',
      description: 'Immune system support supplement',
      price: 150,
      category: ServiceCategory.medicine,
      images: ['https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400'],
      rating: 4.7,
      reviewCount: 41,
      createdAt: DateTime(2024, 1, 1),
      deliveryTime: '15-20 mins',
    ),
    // Furniture
    ServiceModel(
      id: 'fu1',
      providerId: '3',
      providerName: 'Student Furniture Co',
      providerPhone: '01898765432',
      name: 'Study Desk',
      description: 'Compact study desk perfect for students',
      price: 2500,
      category: ServiceCategory.furniture,
      images: ['https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=400'],
      rating: 4.5,
      reviewCount: 23,
      createdAt: DateTime(2024, 1, 1),
      deliveryTime: '1-2 days',
    ),
    ServiceModel(
      id: 'fu2',
      providerId: '3',
      providerName: 'Student Furniture Co',
      providerPhone: '01898765432',
      name: 'Single Bed',
      description: 'Comfortable single bed with mattress',
      price: 4500,
      category: ServiceCategory.furniture,
      images: ['https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=400'],
      rating: 4.6,
      reviewCount: 19,
      createdAt: DateTime(2024, 1, 1),
      deliveryTime: '2-3 days',
    ),
    ServiceModel(
      id: 'fu3',
      providerId: '3',
      providerName: 'Student Furniture Co',
      providerPhone: '01898765432',
      name: 'Bookshelf',
      description: '5-tier wooden bookshelf',
      price: 1800,
      category: ServiceCategory.furniture,
      images: ['https://images.unsplash.com/photo-1594620302200-9a762244a156?w=400'],
      rating: 4.4,
      reviewCount: 15,
      createdAt: DateTime(2024, 1, 1),
      deliveryTime: '1-2 days',
    ),
  ];

  // Demo bookings
  static List<BookingModel> demoBookings = [
    BookingModel(
      id: 'b1',
      houseId: '1',
      studentId: '1',
      studentName: 'Alex Johnson',
      studentPhone: '01712345678',
      status: 'approved',
      createdAt: DateTime.now().subtract(const Duration(days: 5)),
      notes: 'Looking forward to moving in',
    ),
    BookingModel(
      id: 'b2',
      houseId: '2',
      studentId: '1',
      studentName: 'Alex Johnson',
      studentPhone: '01712345678',
      status: 'pending',
      createdAt: DateTime.now().subtract(const Duration(days: 2)),
    ),
  ];

  // Demo orders
  static List<OrderModel> demoOrders = [
    OrderModel(
      id: 'o1',
      serviceId: 'f1',
      studentId: '1',
      studentName: 'Alex Johnson',
      studentPhone: '01712345678',
      studentAddress: 'Room 301, Subang Apartments',
      providerId: '3',
      serviceName: 'Chicken Biryani',
      price: 180,
      quantity: 2,
      status: 'delivered',
      createdAt: DateTime.now().subtract(const Duration(days: 3)),
    ),
    OrderModel(
      id: 'o2',
      serviceId: 'm1',
      studentId: '1',
      studentName: 'Alex Johnson',
      studentPhone: '01712345678',
      studentAddress: 'Room 301, Subang Apartments',
      providerId: '3',
      serviceName: 'Paracetamol 500mg',
      price: 50,
      quantity: 1,
      status: 'confirmed',
      createdAt: DateTime.now().subtract(const Duration(hours: 2)),
    ),
  ];
}
